Latest sources for iOS Push Starter
IBM/ios-push-app pull request #1
Opened 2020-06-07 13:31 UTC by sam-almighty

2020-06-09 18:18 UTC, gee4vee approved these changes

2020-06-09 18:20 UTC, gee4vee commented
Can you add `.DS_Store` to .gitignore please? We don't want those files in source control.

2020-06-10 02:09 UTC, sam-almighty commented
> Can you add `.DS_Store` to .gitignore please? We don't want those files in source control.

Done. Included all the basic ignores.

2020-06-10 02:10 UTC, gee4vee approved these changes

2020-06-11 00:58 UTC, gee4vee requested changes
Found some changes needed.

1. Delete .DS_Store file.
2. Do not delete the `Podfile`. We keep these in our mobile projects for others to use. Is there a particular reason why you deleted it? You can delete the `Podfile.lock` though.
3. Do not include any `xcuserdata` files in source control. Those are for local environments only.
4. See additional comments below.

2020-06-11 01:01 UTC, gee4vee commented on ios-push-app.xcodeproj/xcuserdata/nostanle.xcuserdatad/xcdebugger/Breakpoints_v2.xcbkptlist
> +<?xml version="1.0" encoding="UTF-8"?>
Typically we do not put any of the `xcuserdata` files in source control. Can you remove them?

2020-06-11 01:03 UTC, gee4vee commented on ios-push-app.xcodeproj/xcuserdata/nostanle.xcuserdatad/xcschemes/xcschememanagement.plist
>  <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
Do not include `xcshareddata` either.

2020-06-11 01:05 UTC, gee4vee commented on ios-push-app/Base.lproj/LaunchScreen.storyboard
>  <?xml version="1.0" encoding="UTF-8" standalone="no"?>
We actually need to keep the module name as `iosapp`. The reason is that our code generator does not know about the specific skit name and expects only `iosapp`. We are making a new generation of code generator that will be better, but for now we are avoiding making major changes to the existing one.

2020-06-11 01:05 UTC, gee4vee commented on ios-push-app/CustomUrlButton.swift
> +//
Keep the folder name as `iosapp` (see above).

2020-06-11 01:05 UTC, gee4vee commented on ios-push-app/Info.plist
>  <plist version="1.0">
Keep the folder name as `iosapp` (see above).

2020-06-11 01:05 UTC, gee4vee commented on ios-push-app/SceneDelegate.swift
> +//
Keep the folder name as `iosapp` (see above).

2020-06-11 01:05 UTC, gee4vee commented on ios-push-app/ViewController.swift
> +//
Keep the folder name as `iosapp` (see above).

2020-06-11 01:06 UTC, gee4vee commented on iosappTests/Info.plist
> -<?xml version="1.0" encoding="UTF-8"?>
Keep the folder name as `iosappTests` (see above).

2020-06-11 01:07 UTC, gee4vee commented on iosappTests/iosappTests.swift
> -//
Keep the folder name as `iosappTests` (see above).

2020-06-11 01:07 UTC, gee4vee commented on iosappUITests/Info.plist
> -<?xml version="1.0" encoding="UTF-8"?>
Keep the folder name as `iosappUITests` (see above).

2020-06-11 01:07 UTC, gee4vee commented on iosappUITests/iosappUITests.swift
> -//
Keep the folder name as `iosappUITests` (see above).

2020-06-11 01:08 UTC, gee4vee commented on ios-push-app/AppDelegate.swift
> +//
Keep the folder name as `iosapp` (see above).

2020-06-11 01:08 UTC, gee4vee commented on ios-push-app/Assets.xcassets/AppIcon.appiconset/Contents.json
> +{
Keep the folder name as `iosapp` (see above).

2020-06-11 01:08 UTC, gee4vee commented on ios-push-app/Assets.xcassets/Contents.json
> +{
Keep the folder name as `iosapp` (see above).

2020-07-08 21:32 UTC, youming-lin commented
@sam-almighty Can you take a look at the requested changes? We are looking to deprecate the old mobile starter kits in favor of these new replacements; this repo is one of the replacements.

2020-07-20 16:29 UTC, gee4vee commented
@sam-almighty any update on when you can get to this?

2020-07-27 07:59 UTC, AnanthaKrish commented
I am looking  into this, probably by tomorrow we can close this.

2020-07-29 06:13 UTC, AnanthaKrish commented
Please find the new PR here - https://github.com/IBM/ios-push-app/pull/2

2020-07-29 18:44 UTC, gee4vee commented
Can we close this one in favor of the other? I've added comments to it.

2020-07-30 05:10 UTC, closed without merging